### PR TITLE
Create quickstart.md

### PR DESCRIPTION
**Pull request by antoniomedrano**

### CODE REVIEW

**Comment by glennon** [comment]
I think Getting Started Step 2 can be simplified further. It's probably as easy as:
 `docker run -it -p 80:80 arogi/arogi-demos`

**Comment by antoniomedrano** [comment]
I agree, TSP code shouldn't exist anywhere in this docker

**Comment by glennon** [comment]
I created a new Docker image and updated the instructions. 

Tested on:
- [x] Ubuntu
- [ ] Windows
- [ ] macOS

**Comment by glennon** [comment]
Tests passed. Merging.

**Pull request merged**
