### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by LEDominator**

### CODE REVIEW

**Comment by LEDominator** [comment]
@glennon

**Comment by glennon** [comment]
The release workflow for this repo goes through the development branch before master.

**Comment by LEDominator** [comment]
ok, so that means you want to make the changes to development rather than master?  Just as an FYI I deleted my branch with the changes I made waiting for the pull

**Comment by antoniomedrano** [comment]
@LEDominator Deleting a branch before it's merged I imagine can only lead to bad things.

**Pull request closed without merging**
